
default: &default
  adapter: postgresql
  encoding: unicode

  pool: 5

development:
  <<: *default
  database: explore_further_development

test:
  <<: *default
  database: explore_further_test

production:
  <<: *default
  database: explore_further_production
